# -*- coding: utf-8 -*-

import re

import ply.lex as lex
import ply.yacc as yacc

from .exceptions import IllegalCharacterError, ParseSyntaxError
from .head_tail import TokenValue, head_tail, token_headtail
from .tree import (
    AndOperation, Boost, Fuzzy, Group, Not,
    OrOperation, Phrase, Plus, Prohibit, Proximity,
    Range, To, From, Regex, SearchField, UnknownOperation,
    Word, create_operation, group_to_fieldgroup,
)


reserved = {
  'AND': 'AND_OP',
  'OR': 'OR_OP',
  'NOT': 'NOT',
  'TO': 'TO'}


tokens = (
    ['TERM',
     'PHRASE',
     'REGEX',
     'APPROX',
     'BOOST',
     'MINUS',
     'PLUS',
     'COLUMN',
     'LPAREN',
     'RPAREN',
     'LBRACKET',
     'RBRACKET',
     'LESSTHAN',
     'GREATERTHAN'] +
    sorted(list(reserved.values())))


precedence = (
    ('left', 'IMPLICIT_OP'),
    ('left', 'OR_OP'),
    ('left', 'AND_OP'),
    ('nonassoc', 'PLUS', 'MINUS'),
    ('nonassoc', 'BOOST'),
    ('nonassoc', 'TO'),
    ('right', 'UMINUS')
)


TIME_RE = r'''
(?<=T\d{2}):  # look behind for T and two digits: hours
\d{2}         # minutes
(:\d{2})?     # seconds
'''

TERM_RE = r'''
(?P<term>  # group term
  (?:
   [^\s:^~(){{}}[\]/"'+\-\\<>] # first char is not a space neither some char which have meanings
                              # note: escape of "-" and "]"
                              #       and doubling of "{{}}" (because we use format)
   |                          # but
   \\.                        # we can start with an escaped character
  )
  ([^\s:^\\~(){{}}[\]]        # following chars
   |                          # OR
   \\.                        # an escaped char
   |                          # OR
   {time_re}                  # a time expression
  )*
)
'''.format(time_re=TIME_RE)

PHRASE_RE = r'''
(?P<phrase>  # phrase
  "          # opening quote
  (?:        # repeating
    [^\\"]   # - a char which is not escape or end of phrase
    |        # OR
    \\.      # - an escaped char
  )*
  "          # closing quote
)'''
APPROX_RE = r'~(?P<degree>[0-9.]+)?'
BOOST_RE = r'\^(?P<force>[0-9.]+)?'

REGEX_RE = r'''
(?P<regex>  # regex
  /         # open slash
  (?:       # repeating
    [^\\/]  # - a char which is not escape or end of regex
    |       # OR
    \\.     # an escaped char
  )*
  /         # closing slash
)'''


def t_SEPARATOR(t):
    pass



@lex.TOKEN(TERM_RE)
def t_TERM(t):
    pass


def simple_token(t):
    pass


def t_PLUS(t):
    pass


def t_MINUS(t):
    pass


def t_COLUMN(t):
    pass


def t_LPAREN(t):
    pass


def t_RPAREN(t):
    pass


def t_LBRACKET(t):
    pass


def t_RBRACKET(t):
    pass


def t_GREATERTHAN(t):
    pass


def t_LESSTHAN(t):
    pass


@lex.TOKEN(PHRASE_RE)
def t_PHRASE(t):
    pass


@lex.TOKEN(REGEX_RE)
def t_REGEX(t):
    pass


@lex.TOKEN(APPROX_RE)
def t_APPROX(t):
    pass


@lex.TOKEN(BOOST_RE)
def t_BOOST(t):
    pass


def t_error(t):
    raise IllegalCharacterError("Illegal character '%s' at position %d" % (t.value, t.lexpos))


lexer = lex.lex()


def p_expression_or(p):
    pass


def p_expression_and(p):
    pass


def p_expression_implicit(p):
    pass


def p_expression_plus(p):
    pass


def p_expression_minus(p):
    pass


def p_expression_not(p):
    pass


def p_expression_unary(p):
    pass


def p_grouping(p):
    pass


def p_range(p):
    pass


def p_possibly_negative_term(p):
    pass


def p_phrase_or_possibly_negative_term(p):
    pass


def p_lessthan(p):
    pass


def p_greaterthan(p):
    pass


def p_field_search(p):
    pass


def p_quoting(p):
    pass


def p_proximity(p):
    pass


def p_boosting(p):
    pass


def p_terms(p):
    pass


def p_fuzzy(p):
    pass


def p_regex(p):
    pass


def p_to_as_term(p):
    pass


def p_phrase_or_term(p):
    pass


def p_error(p):
    pass


parser = yacc.yacc()
"""This is the parser generated by PLY


**Note**: The parser by itself is not thread safe (because PLY is not).
Use :py:func:`luqum.thread.parse` instead
"""

_orig_parse = parser.parse


def parse(input=None, lexer=lexer, debug=False, tracking=False, tokenfunc=None):
    """
    A function to parse a text Lucene query provided as ``input``.

    The function signature is based on :func:`ply.yacc.LRParser.parse` except
    that ``lexer`` default to :data:`luqum.parser.lexer`.
    """
    return _orig_parse(
        input=input, lexer=lexer, debug=debug, tracking=tracking, tokenfunc=tokenfunc
    )


parser.parse = parse
